kind: Service
apiVersion: v1
metadata:
  name: spring-boot-training
spec:
  type: LoadBalancer
  selector:
    app: spring-boot-training
  ports:
    - name: http
      protocol: TCP
      port: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-training
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-training
  template:
    metadata:
      labels:
        app: spring-boot-training
    spec:
      containers:
        - name: spring-boot-training
          image: jorekai/spring-boot-training:latest